spring.application.name=DriveEasy

spring.datasource.url=jdbc:mysql://localhost:3306/driveeasy_db
spring.datasource.username=root
spring.datasource.password=Tusharp4488.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true